### ISSUE TITLE
Discuss the issue of inheritance

### ISSUE THREAD

**Issue by mwhooker** [core/uricore#1]
I think the way the lib works now, with URI composing IRI, is broken.

I'd like to discuss this more and decide on the right direction.

My complaints are:
- no way to pass query_cls to URI
- further inheritance will be difficult (**getattr** can shadow attributes and just obfuscates the whole thing.)
- redundant behavior.
- if URI satisfies the "is-a" for IRI, it should subclass IRI.

essentially the only thing that URI has to do differently is representation and encoding. I'm sure we can easily isolate these two things and come to an elegant solution.

**Comment by brainsik** [comment]
Not sure if you saw my reply to your commit comment. I totally agree the current way is broken and I almost finished making URI subclass IRI but had to leave Pycon before I was done. I've been thinking a lot about the Right Way to do this and I have a new take that satisfies all these concerns.
