### ISSUE TITLE
implement rfc6570 (URI Templates)

### ISSUE THREAD

**Issue by mwhooker** [core/uricore#2]
Multiple people have requested this, and since it falls under "URIs", let's give it a whack.

http://tools.ietf.org/html/rfc6570

will update here as we look into it.

**Comment by kennethreitz** [comment]
:cake:

**Comment by glyphobet** [comment]
Who has requested this? Have they just requested that some Python library support URI Templates, or specifically that uricore support them?

**Comment by glyphobet** [comment]
I've taken a look at the URI Templates spec; are Python programmers really going to want to learn yet another string templating mini-language, or are they just going to create URIs with `%` or `.format()` ?

**Comment by kennethreitz** [comment]
Well, if they're standardized, they could be quite useful.

Imagine an API of some sort specifying a template to use for a given resource, etc.

**Comment by glyphobet** [comment]
Do you mean that an external API would specify a URI Template using the spec, for a resource, and then that template could be passed to uricore to generate URLs? I can see how that would be useful, but do any APIs out there actually do that? I'm just skeptical of spending the time to implement something without a clear need.
